name: release

on:
  push:
    branches:
      - main
      - release
      - test

env:
  NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

permissions:
  id-token: write
  contents: write
  pull-requests: write
  issues: write
  checks: write

jobs:
  pre-flight:
    name: Pre-flight
    runs-on: ubuntu-latest
    steps:
      - uses: danielchabr/pr-labels-checker@v3.1
        with:
          hasNone: dependencies
          githubToken: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
        id: dependabot-label
      - uses: danielchabr/pr-labels-checker@v3.1
        with:
          hasAll: dependencies,ok-to-test
          githubToken: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.dependabot-label.outcome != 'success' }}

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Release
        uses: codfish/semantic-release-action@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}